version: "3"

secrets:
  password:
    file: ./secrets/password

services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - /path/to/data:/app/data
    ports:
      - 5005:5005
    secrets:
      - password
    environment:
      - PASSWORD_FILE=/run/secrets/password
    restart: unless-stopped
